# Generated by Django 5.2.7 on 2025-12-08 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='hours_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='entry',
            name='study_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
